### ISSUE TITLE
Add unmanaged encryption benchmark

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide-scala#42]
As a ironoxide-scala user
I want to understand the performance characteristics of unmanaged encryption 

AC
* [x] benchmark exists that shows unmanaged encryption to self. This should not utilize the network.

**Comment by coltfred** [comment]
This was addressed by using https://github.com/IronCoreLabs/scala-stress/pull/20 and tweaking the configuration.

**Comment by coltfred** [comment]
We also did throughput tests using this.
