### ISSUE TITLE
Standardize namespaces

### ISSUE THREAD

**Issue by giarc3** [IronCoreLabs/ironoxide-scala#50]
We've never had a "correct" folder hierarchy -> namespace correlation. We should make these line up while also making any improvements we want to our namespace.

Suggestions discussed:
- Scala namespace: ~~com.ironcorelabs.scala.sdk~~ -> ironoxide
- Put things like the sdk object into the root namespace, and make other natural namespaces for things like documents, users, groups, etc.
- Make the folders in the repo match the namespace exactly.
- Possibly add a version number at the end of the namespace for compatibility like we have in `tenant-security-client-java`
- Rename `IronSdk*` to `IronOxide*` to be more consistent among repos and use our own terminology more

If I've forgotten some changes, add them in a comment.

**Comment by coltfred** [comment]
> Scala namespace: com.ironcorelabs.scala.sdk -> ironoxide

I think this is a good idea.

> Put things like the sdk object into the root namespace, and make other natural namespaces for things like documents, users, groups, etc.

I agree that they should be separated into logical chunks. They should have singular names, though. `document` `user` etc.

> Make the folders in the repo match the namespace exactly.

Yes, please!

> Possibly add a version number at the end of the namespace for compatibility like we have in tenant-security-client-java

It seems like this is also a good idea. On the JVM there isn't a great strategy for having multiple versions of a dependency so if we imagine that people will have data that they need to decrypt with V1 and encrypt with V2 at some point in the future we should plan for that now.

> Rename IronSdk* to IronOxide* to be more consistent among repos and use our own terminology more

Seems like this is reasonable. At first I thought this might seem odd to users in Scala, but a name is just a name... It's funny in Rust and here it's just *the name*.
